(function(){
  'use strict'; const M=window.GAT,$=id=>document.getElementById(id);
  const state={sequence:[],current:0,selected:-1,dirty:false,preference:'sharp',tones:[],chords:[],range:[5,9],playing:false,playState:'stopped',customTunings:{}};
  const defaults={tuning:'standard',root:'C',category:'七和弦',chordType:'m7',accidental:'auto',practiceMode:'single',progression:'Cm7 | Fm7 | Bb7 | Ebmaj7',positionMode:'fixed',minFret:5,maxFret:9,cagedShape:'C',cagedStrict:'strict',direction:'updown',startDegree:'root',inversion:'0',pattern:'1-3-5-7',customPattern:'1 3 5 7 9 7 5 3',bpm:90,timeSignature:'4/4',noteValue:'2',chordBeats:4,swing:'0.5',metronome:true,countIn:false,loop:true,masterVolume:.8,arpVolume:.72,metroVolume:.35,sustain:.65,displayMode:'both',viewMode:'all',presetName:'我的琶音练习'};
  const settingIds=Object.keys(defaults);
  function notify(message,type=''){const n=$('notice');n.textContent=message;n.className='notice '+type;}
  function pathError(message){const n=$('notice');n.textContent=message+' ';n.className='notice error';[['relax','放宽把位'],['full','允许跨把位'],['shorter','减少音序长度']].forEach(([action,label])=>{const b=document.createElement('button');b.type='button';b.className='small';b.dataset.recovery=action;b.textContent=label;n.appendChild(b)})}
  function setValue(id,value){const e=$(id);if(!e)return;if(e.type==='checkbox')e.checked=!!value;else e.value=value;}
  function values(){const o={};settingIds.forEach(id=>{const e=$(id);if(e)o[id]=e.type==='checkbox'?e.checked:e.value});return o;}
  function applyValues(o){if(o?.category)setValue('category',o.category);updateChordTypes();Object.entries(o||{}).forEach(([k,v])=>{if(k!=='category')setValue(k,v)});syncControls();}
  function fillSelects(){
    try{Object.assign(M.CHORDS,JSON.parse(localStorage.getItem('gat-custom-chords')||'{}'))}catch(_){}
    $('tuning').innerHTML=Object.entries(M.TUNINGS).map(([k,v])=>`<option value="${k}">${v.name}</option>`).join('')+'<option value="custom">自定义调弦</option>';
    $('root').innerHTML=M.NOTES_SHARP.map((n,i)=>`<option value="${n}">${n}${M.NOTES_FLAT[i]!==n?' / '+M.NOTES_FLAT[i]:''}</option>`).join('');
    $('category').innerHTML=M.CATEGORIES.map(c=>`<option>${c}</option>`).join('');
    $('rangeShortcuts').innerHTML=[[0,4],[1,5],[3,7],[5,9],[7,11],[8,12],[10,14],[12,16],[15,19],[0,24]].map(r=>`<button type="button" data-range="${r}">${r[0]===0&&r[1]===24?'全指板':r.join('–')}</button>`).join('');
    $('editString').innerHTML=[1,2,3,4,5,6].map(n=>`<option value="${n}">${n} 弦</option>`).join('');
    $('customDegrees').innerHTML=Object.keys(M.DEGREE_INTERVALS).map((d,i)=>`<label><input type="checkbox" value="${d}" ${i===0?'checked disabled':''}>${d}</label>`).join('');
    state.customTunings=JSON.parse(localStorage.getItem('gat-custom-tunings')||'{}');
    buildCustomTuning(state.customTunings.last||M.TUNINGS.standard.midi);
    updateChordTypes();refreshPresetList();
  }
  function buildCustomTuning(midi){$('customTuning').innerHTML=midi.map((v,i)=>`<label>${i+1} 弦 MIDI<input class="tuning-midi" type="number" min="24" max="88" value="${v}"></label>`).join('')}
  function updateChordTypes(){const cat=$('category').value||defaults.category,old=$('chordType').value;const entries=Object.entries(M.CHORDS).filter(([,c])=>c.category===cat);$('chordType').innerHTML=entries.length?entries.map(([k,c])=>`<option value="${k}">${c.name} (${c.symbol||'maj'})</option>`).join(''):'<option value="">请先创建自定义和弦</option>';if(entries.some(([k])=>k===old))$('chordType').value=old;if($('customChordBox'))$('customChordBox').classList.toggle('hidden',cat!=='自定义和弦');}
  function tuningMidi(){if($('tuning').value==='custom')return [...document.querySelectorAll('.tuning-midi')].map(e=>Number(e.value));return M.TUNINGS[$('tuning').value].midi.slice()}
  function accidental(){
    if($('accidental').value!=='auto')return $('accidental').value;
    if($('root').value.includes('#'))return 'sharp';
    if(['min','dim','m7','mMaj7','m7b5','dim7','m9','m11','m13','m6','madd9','m6/9'].includes($('chordType').value))return 'flat';
    return 'sharp';
  }
  function parseProgression(){
    if($('practiceMode').value==='single')return [{root:M.parseNote($('root').value),chordKey:$('chordType').value,accidental:accidental()}];
    const parts=$('progression').value.split(/[|,]/).map(s=>s.trim()).filter(Boolean);if(!parts.length)throw new Error('和弦进行不能为空。');
    return parts.map(text=>{const p=M.parseChordSymbol(text);if(!p)throw new Error(`无法识别和弦“${text}”，示例：Cm7、F7、Bbmaj7。`);return {...p,accidental:M.resolveAccidental(p.rootText,$('accidental').value)};});
  }
  function calculateRange(chords){
    let min=Number($('minFret').value),max=Number($('maxFret').value);const mode=$('positionMode').value;
    if(mode==='caged'){const root=chords[0].root,offset={C:0,A:3,G:5,E:8,D:10}[$('cagedShape').value];let center=M.mod(root-offset);while(center<2)center+=12;min=Math.max(0,center-2);max=Math.min(24,center+2);if($('cagedStrict').value==='expand'){min=Math.max(0,min-2);max=Math.min(24,max+2)}}
    if(mode==='auto'){
      let best={score:Infinity,min:0,max:4};for(let s=0;s<=19;s++){const tones=M.chordTones(chords[0].root,chords[0].chordKey),c=M.Fretboard.candidates(tuningMidi(),tones,s,s+5),pcs=new Set(c.map(n=>n.pitchClass)),roots=c.filter(n=>n.degree==='1').length,score=(tones.length-pcs.size)*100-roots*4+c.length*.08+(s===0?8:0);if(score<best.score)best={score,min:s,max:s+5}}min=best.min;max=best.max;
    }
    if(!Number.isInteger(min)||!Number.isInteger(max)||min<0||max>24||min>=max)throw new Error('品位范围无效：最低品必须小于最高品，且范围为 0–24。');return [min,max];
  }
  function generate(){
    try{const locked=new Map(state.sequence.filter(n=>n.locked).map(n=>[n.index,n]));transport.stop(false);const bpm=Number($('bpm').value);if(bpm<30||bpm>300)throw new Error('BPM 必须在 30–300 之间。');const chords=parseProgression();let range=calculateRange(chords);const [beatsPerBar]=$('timeSignature').value.split('/').map(Number),notesPerBeat=Number($('noteValue').value),pattern=$('pattern').value==='custom'?$('customPattern').value:$('pattern').value;
      if(!pattern.trim()||!/^[0-9♭♯b#\s-]+$/.test(pattern))throw new Error('自定义音序为空或包含无效字符。');chords.forEach(c=>{c.beatsPerBar=beatsPerBar});
      const requestFor=r=>({chords,tuning:tuningMidi(),minFret:r[0],maxFret:r[1],direction:$('direction').value,pattern,notesPerBeat,chordBeats:Number($('chordBeats').value),inversion:$('inversion').value,startDegree:$('startDegree').value});let sequence;
      try{sequence=M.SequenceEngine.generate(requestFor(range))}catch(initialError){
        if($('positionMode').value!=='auto')throw initialError;
        const choices=[];for(const width of [5,7,9,12,24])for(let start=0;start+width<=24;start++){const candidateRange=[start,start+width];try{const seq=M.SequenceEngine.generate(requestFor(candidateRange)),movement=seq.slice(1).reduce((sum,n,i)=>sum+Math.abs(n.fret-seq[i].fret),0),score=movement+width*1.5+Math.abs((start+width/2)-7)*.35;choices.push({seq,range:candidateRange,score})}catch(_){}}
        if(!choices.length)throw initialError;choices.sort((a,b)=>a.score-b.score);sequence=choices[0].seq;range=choices[0].range;
      }
      sequence=sequence.map((n,i)=>{const old=locked.get(i);return old&&old.fret>=range[0]&&old.fret<=range[1]&&old.chordIndex===n.chordIndex?{...old,index:i}:n});
      state.sequence=sequence;state.current=0;transport.load(sequence);state.chords=chords;state.range=range;state.preference=accidental();state.tones=M.chordTones(chords[0].root,chords[0].chordKey);state.dirty=false;$('controls').classList.remove('dirty');if($('positionMode').value==='caged')$('cagedRange').textContent=`当前 ${$('cagedShape').value} 型覆盖 ${range[0]}–${range[1]} 品`;const jumps=sequence.slice(1).map((n,i)=>({fret:Math.abs(n.fret-sequence[i].fret),string:Math.abs(n.string-sequence[i].string),midi:n.midi-sequence[i].midi})),coverage=Math.min(...chords.map((_,chordIndex)=>new Set(sequence.filter(n=>n.chordIndex===chordIndex).map(n=>n.string)).size));document.body.dataset.sequenceQa=JSON.stringify({count:sequence.length,stringCoverage:coverage,stringPath:sequence.slice(0,18).map(n=>n.string),minFret:Math.min(...sequence.map(n=>n.fret)),maxFret:Math.max(...sequence.map(n=>n.fret)),maxFretJump:Math.max(0,...jumps.filter((_,i)=>sequence[i].chordIndex===sequence[i+1].chordIndex).map(j=>j.fret)),maxStringJump:Math.max(0,...jumps.filter((_,i)=>sequence[i].chordIndex===sequence[i+1].chordIndex).map(j=>j.string)),sameStringMax:sequence.reduce((a,n,i)=>{const run=i&&sequence[i-1].string===n.string&&sequence[i-1].chordIndex===n.chordIndex?a.run+1:1;return {run,max:Math.max(a.max,run)}},{run:0,max:0}).max,descending:jumps.filter(j=>j.midi<0).length,ascending:jumps.filter(j=>j.midi>0).length,outside:sequence.filter(n=>n.fret<range[0]||n.fret>range[1]).length});render();notify(`已生成 ${sequence.length} 个音；每个和弦覆盖 6 根弦，位于 ${range[0]}–${range[1]} 品。`);
    }catch(e){if(/无法|没有可用位置/.test(e.message))pathError(e.message);else notify(e.message,'error');}
  }
  function currentContext(index=state.current){const n=state.sequence[index]||null,next=state.sequence[(index+1)%Math.max(1,state.sequence.length)]||null,prev=state.sequence[index-1]||null;return {n,next,prev};}
  function render(){
    const {n,next,prev}=currentContext(),beatsPerBar=Number($('timeSignature').value.split('/')[0]),npb=Number($('noteValue').value),chord=n?state.chords[n.chordIndex]:state.chords[0];if(!chord)return;
    const tones=M.chordTones(chord.root,chord.chordKey);state.tones=tones;$('currentChord').textContent=n?.chordName||M.formatChord(chord.root,chord.chordKey,state.preference);$('transportChord').textContent=$('currentChord').textContent;$('chordNotes').textContent=tones.map(t=>M.noteName(t.pitchClass,state.preference)).join(' · ');$('positionStat').textContent=state.range.join('–');$('sequenceStat').textContent=state.sequence.length+' 音';$('tempoStat').textContent=$('bpm').value+' BPM';$('fretRangeLabel').textContent=state.range.join('–')+' 品';
    if(n){$('nowNote').textContent=M.noteWithOctave(n.midi,state.preference);$('nowDegree').textContent=n.degree+(n.degree==='1'?' · 根音':'');$('nowPosition').textContent=`${n.string} 弦 · ${n.fret} 品`;$('nowFinger').textContent=n.finger===0?'空弦':'建议 '+n.finger+' 指';$('nextNote').textContent=next?M.noteWithOctave(next.midi,state.preference):'—';$('nextPosition').textContent=next?`${next.string} 弦 · ${next.fret} 品`:'练习结束';const beat=Math.floor(n.beatInChord)%beatsPerBar+1,totalBars=Math.max(...state.sequence.map(x=>x.bar))+1;$('nowBeat').textContent=`${beat} / ${beatsPerBar}`;$('nowBar').textContent=`第 ${n.bar+1} 小节`;$('barInfo').textContent=`小节 ${n.bar+1} / ${totalBars}`;$('beatInfo').textContent=`拍 ${beat} / ${beatsPerBar}`;const label={playing:'播放中',paused:'已暂停',stopped:'已停止'}[state.playState];$('transportStatus').textContent=`${label} · ${state.current+1} / ${state.sequence.length}`;$('progressBar').style.width=((state.current+1)/state.sequence.length*100)+'%';}
    M.TabRenderer.render($('tabCanvas'),state.sequence,state.current,beatsPerBar,npb);M.FretboardRenderer.render($('fretboardCanvas'),{tuning:tuningMidi(),tones,minFret:state.range[0],maxFret:state.range[1],current:n,next,previous:prev,displayMode:$('displayMode').value,preference:state.preference});
  }
  const transport=new M.Transport({visual(index){state.current=index;render();const b=$('beatCard');b.classList.remove('active');void b.offsetWidth;b.classList.add('active')},state(mode){state.playState=mode;state.playing=mode==='playing';$('playBtn').textContent=mode==='playing'?'Ⅱ 暂停':mode==='paused'?'▶ 继续':'▶ 开始';render();}});
  function transportSettings(){return {bpm:()=>Number($('bpm').value),notesPerBeat:()=>Number($('noteValue').value),beatsPerBar:()=>Number($('timeSignature').value.split('/')[0]),swing:()=>Number($('swing').value),loop:()=>$('loop').checked,metronome:()=>$('metronome').checked,countIn:()=>$('countIn').checked,master:()=>Number($('masterVolume').value),arp:()=>Number($('arpVolume').value),metro:()=>Number($('metroVolume').value),sustain:()=>Number($('sustain').value)}}
  async function togglePlay(){try{if(!state.sequence.length)generate();if(state.playing)transport.pause();else await transport.resume(state.sequence,transportSettings())}catch(e){notify(e.message,'error')}}
  function markDirty(e){const live=['bpm','bpmRange','masterVolume','arpVolume','metroVolume','sustain','displayMode','viewMode','loop','metronome'];if(live.includes(e.target.id)){if(e.target.id==='bpmRange')$('bpm').value=e.target.value;if(e.target.id==='bpm')$('bpmRange').value=e.target.value;syncControls();render();return}state.dirty=true;$('controls').classList.add('dirty');notify('参数已变化，请重新生成。','warning');syncControls();}
  function syncControls(){
    $('customTuning').classList.toggle('hidden',$('tuning').value!=='custom');$('saveTuningBtn').classList.toggle('hidden',$('tuning').value!=='custom');$('customChordBox').classList.toggle('hidden',$('category').value!=='自定义和弦');$('progressionBox').classList.toggle('hidden',$('practiceMode').value!=='progression');$('fixedPosition').classList.toggle('hidden',$('positionMode').value!=='fixed');$('cagedPosition').classList.toggle('hidden',$('positionMode').value!=='caged');$('customPatternLabel').classList.toggle('hidden',$('pattern').value!=='custom');document.body.classList.remove('view-tab','view-fretboard');if($('viewMode').value!=='all')document.body.classList.add('view-'+$('viewMode').value);$('tuningLabel').textContent=$('tuning').selectedOptions[0]?.textContent||'自定义调弦';
  }
  function changeBpm(delta){$('bpm').value=Math.max(30,Math.min(300,Number($('bpm').value)+delta));$('bpmRange').value=$('bpm').value;render()}
  function setTheme(mode){const actual=mode==='system'?(matchMedia('(prefers-color-scheme: dark)').matches?'dark':'light'):mode;document.documentElement.dataset.theme=actual;document.body.dataset.themeMode=mode;$('themeBtn').title='主题：'+({dark:'深色',light:'浅色',system:'跟随系统'}[mode]);localStorage.setItem('gat-theme',mode);render()}
  let taps=[];function tap(){const t=performance.now();taps=taps.filter(x=>t-x<2500).concat(t);if(taps.length>1){const avg=(taps[taps.length-1]-taps[0])/(taps.length-1);$('bpm').value=Math.max(30,Math.min(300,Math.round(60000/avg)));$('bpmRange').value=$('bpm').value;render()}}
  function refreshPresetList(selected=''){const all=M.Presets.list();$('presetList').innerHTML='<option value="">— 未选择 —</option>'+Object.keys(all).sort().map(n=>`<option>${n}</option>`).join('');$('presetList').value=selected}
  function exportPreset(){const blob=new Blob([JSON.stringify({version:1,settings:values(),sequence:state.sequence},null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=($('presetName').value||'arpeggio-preset')+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
  function progressionTemplate(value){const r=M.parseNote($('root').value);if(!value)return;let items;if(value==='blues')items=[1,1,1,1,4,4,1,1,5,4,1,5];else if(value==='cycle')items=[1,4,7,3,6,2,5,1];else items=value.split(',');$('progression').value=items.map(x=>{const num=parseInt(x),suffix=x.replace(String(num),'');return M.noteName(r+([0,2,4,5,7,9,11][num-1]),accidental())+(suffix==='m'?'m':suffix==='dim'?'m7b5':suffix==='maj7'?'maj7':num===5?'7':'')}).join(' | ');$('practiceMode').value='progression';syncControls()}
  function bind(){
    document.querySelectorAll('.controls input,.controls select').forEach(e=>e.addEventListener('change',markDirty));$('category').addEventListener('change',updateChordTypes);$('generateBtn').addEventListener('click',generate);$('playBtn').addEventListener('click',togglePlay);$('stopBtn').addEventListener('click',()=>transport.stop());$('rewindBtn').addEventListener('click',()=>transport.setIndex(0));$('prevBarBtn').addEventListener('click',()=>transport.setIndex(Math.max(0,state.current-Number($('timeSignature').value.split('/')[0])*Number($('noteValue').value))));$('nextBarBtn').addEventListener('click',()=>transport.setIndex(state.current+Number($('timeSignature').value.split('/')[0])*Number($('noteValue').value)));$('bpmDown').onclick=()=>changeBpm(-5);$('bpmUp').onclick=()=>changeBpm(5);$('tapBtn').onclick=tap;
    $('rangeShortcuts').onclick=e=>{const r=e.target.dataset.range;if(r){[$('minFret').value,$('maxFret').value]=r.split(',');markDirty({target:$('minFret')})}};$('progressionTemplate').onchange=e=>progressionTemplate(e.target.value);
    $('notice').onclick=e=>{const action=e.target.dataset.recovery;if(!action)return;if(action==='relax'){$('minFret').value=Math.max(0,Number($('minFret').value)-2);$('maxFret').value=Math.min(24,Number($('maxFret').value)+2)}else if(action==='full'){$('positionMode').value='fixed';$('minFret').value=0;$('maxFret').value=24}else if(action==='shorter')$('chordBeats').value=Math.max(1,Math.ceil(Number($('chordBeats').value)/2));syncControls();generate()};
    $('themeBtn').onclick=()=>{const modes=['dark','light','system'],current=document.body.dataset.themeMode||'dark';setTheme(modes[(modes.indexOf(current)+1)%modes.length])};$('focusBtn').onclick=()=>document.body.classList.toggle('focus');$('panelToggle').onclick=()=>document.body.classList.toggle('panel-open');$('fullscreenBtn').onclick=()=>document.fullscreenElement?document.exitFullscreen():document.documentElement.requestFullscreen();$('helpBtn').onclick=()=>$('helpDialog').showModal();$('closeHelp').onclick=()=>$('helpDialog').close();
    $('tabCanvas').onclick=e=>{const i=M.TabRenderer.hitTest($('tabCanvas'),e,state.sequence,state.current);if(i<0)return;state.selected=i;$('editString').value=state.sequence[i].string;$('editFret').value=state.sequence[i].fret;$('noteEditor').classList.remove('hidden')};$('closeEditor').onclick=()=>$('noteEditor').classList.add('hidden');
    $('applyEdit').onclick=()=>{const n=state.sequence[state.selected],string=Number($('editString').value),fret=Number($('editFret').value);if(!n||fret<0||fret>24)return notify('编辑品位必须在 0–24。','error');const midi=tuningMidi()[string-1]+fret;state.sequence[state.selected]={...n,string,fret,midi,pitchClass:M.mod(midi),degree:M.chordTones(n.root,n.chordKey).find(t=>t.pitchClass===M.mod(midi))?.degree||'非和弦音',locked:true};render();notify('已应用手动编辑并锁定该音。')};
    $('deleteNote').onclick=()=>{state.sequence.splice(state.selected,1);state.sequence.forEach((n,i)=>n.index=i);state.current=Math.min(state.current,state.sequence.length-1);$('noteEditor').classList.add('hidden');render()};
    const insert=after=>{const n=state.sequence[state.selected];if(!n)return;state.sequence.splice(state.selected+(after?1:0),0,{...n,locked:true});state.sequence.forEach((x,i)=>x.index=i);render()};$('insertBefore').onclick=()=>insert(false);$('insertAfter').onclick=()=>insert(true);$('lockNote').onclick=()=>{const n=state.sequence[state.selected];if(n){n.locked=!n.locked;$('lockNote').textContent=n.locked?'解除锁定':'锁定';render()}};$('regenBar').onclick=()=>{const bar=state.sequence[state.selected]?.bar;generate();const i=state.sequence.findIndex(n=>n.bar===bar);if(i>=0)state.current=i;render()};
    $('savePreset').onclick=()=>{try{M.Presets.save($('presetName').value,{settings:values(),sequence:state.sequence});refreshPresetList($('presetName').value);$('presetLabel').textContent=$('presetName').value;notify('方案已保存到本机。')}catch(e){notify(e.message,'error')}};$('saveAsPreset').onclick=()=>{const base=$('presetName').value||'我的练习';$('presetName').value=base+' 副本';$('savePreset').click()};$('newPreset').onclick=()=>{applyValues(defaults);generate();$('presetLabel').textContent='未命名方案'};$('presetList').onchange=e=>{const p=M.Presets.load(e.target.value);if(p){applyValues(p.settings);state.sequence=p.sequence||[];$('presetName').value=e.target.value;$('presetLabel').textContent=e.target.value;state.current=0;state.chords=parseProgression();state.range=calculateRange(state.chords);render()}};$('deletePreset').onclick=()=>{const n=$('presetList').value||$('presetName').value;if(n&&confirm(`删除方案“${n}”？`)){M.Presets.remove(n);refreshPresetList();notify('方案已删除。')}};$('renamePreset').onclick=()=>{const old=$('presetList').value,newName=$('presetName').value;try{M.Presets.rename(old,newName);refreshPresetList(newName);$('presetLabel').textContent=newName}catch(e){notify(e.message,'error')}};$('exportPreset').onclick=exportPreset;$('importPreset').onclick=()=>$('importFile').click();$('importFile').onchange=async e=>{try{const data=M.Presets.validate(JSON.parse(await e.target.files[0].text()));applyValues(data.settings);state.sequence=data.sequence||[];generate();notify('方案导入成功。')}catch(err){notify('导入失败：'+err.message,'error')}};$('resetPreset').onclick=()=>{if(confirm('恢复默认设置？当前未保存更改会丢失。')){$('newPreset').click()}};
    $('saveTuningBtn').onclick=()=>{const midi=tuningMidi();if(midi.some((n,i)=>!Number.isInteger(n)||n<24||n>88||(i&&n>=midi[i-1])))return notify('自定义调弦必须是 1 弦到 6 弦依次降低、范围 24–88 的整数 MIDI。','error');localStorage.setItem('gat-custom-tunings',JSON.stringify({last:midi}));notify('自定义调弦已保存。')};
    $('saveCustomChord').onclick=()=>{try{const name=$('customChordName').value.trim(),degrees=[...$('customDegrees').querySelectorAll('input:checked')].map(e=>e.value);if(!name)throw new Error('请输入自定义和弦名称。');if(degrees.length<2)throw new Error('自定义和弦至少需要根音之外的一个级数。');const key='custom_'+name.replace(/\s+/g,'_'),item={name,category:'自定义和弦',symbol:name,intervals:degrees.map(d=>M.DEGREE_INTERVALS[d]),degrees};M.CHORDS[key]=item;const stored=JSON.parse(localStorage.getItem('gat-custom-chords')||'{}');stored[key]=item;localStorage.setItem('gat-custom-chords',JSON.stringify(stored));updateChordTypes();$('chordType').value=key;notify(`自定义和弦“${name}”已保存。`)}catch(e){notify(e.message,'error')}};
    $('deleteCustomChord').onclick=()=>{const key=$('chordType').value;if(!key.startsWith('custom_'))return notify('请选择要删除的自定义和弦。','error');delete M.CHORDS[key];const stored=JSON.parse(localStorage.getItem('gat-custom-chords')||'{}');delete stored[key];localStorage.setItem('gat-custom-chords',JSON.stringify(stored));updateChordTypes();notify('自定义和弦已删除。')};
    $('randomizeBtn').onclick=()=>{const roots=M.NOTES_SHARP,all=Object.keys(M.CHORDS).filter(k=>!k.startsWith('custom_'));$('root').value=roots[Math.floor(Math.random()*roots.length)];const key=all[Math.floor(Math.random()*all.length)],ch=M.CHORDS[key];$('category').value=ch.category;updateChordTypes();$('chordType').value=key;const start=Math.floor(Math.random()*16);$('minFret').value=start;$('maxFret').value=start+5;const dirs=['up','down','updown','downup'];$('direction').value=dirs[Math.floor(Math.random()*dirs.length)];$('startDegree').value=['root','lowest','highest','random'][Math.floor(Math.random()*4)];$('practiceMode').value='single';syncControls();generate()};
    window.addEventListener('resize',render);document.addEventListener('visibilitychange',()=>{if(document.hidden&&state.playing){transport.pause();notify('页面进入后台，已自动暂停以避免时间轴错位。','warning')}});document.addEventListener('keydown',e=>{if(/INPUT|SELECT|TEXTAREA/.test(e.target.tagName))return;const k=e.key.toLowerCase();if(e.key===' '){e.preventDefault();togglePlay()}else if(e.key==='Escape')transport.stop();else if(k==='r')transport.setIndex(0);else if(e.key==='ArrowLeft')transport.setIndex(state.current-1);else if(e.key==='ArrowRight')transport.setIndex(state.current+1);else if(e.key==='ArrowUp')changeBpm(5);else if(e.key==='ArrowDown')changeBpm(-5);else if(k==='f')$('fullscreenBtn').click();else if(k==='l')$('loop').checked=!$('loop').checked;else if(k==='m')$('metronome').checked=!$('metronome').checked});
  }
  window.GAT_TESTS={run(){const failures=[];const eq=(name,a,b)=>{if(JSON.stringify(a)!==JSON.stringify(b))failures.push(`${name}: ${JSON.stringify(a)} ≠ ${JSON.stringify(b)}`)};eq('Cm7',M.chordTones(0,'m7').map(x=>x.pitchClass),[0,3,7,10]);eq('Cmaj7',M.chordTones(0,'maj7').map(x=>x.pitchClass),[0,4,7,11]);eq('C7',M.chordTones(0,'7').map(x=>x.pitchClass),[0,4,7,10]);eq('Cm7b5',M.chordTones(0,'m7b5').map(x=>x.pitchClass),[0,3,6,10]);eq('Cdim7',M.chordTones(0,'dim7').map(x=>x.pitchClass),[0,3,6,9]);eq('Cmaj9',M.chordTones(0,'maj9').map(x=>x.pitchClass),[0,4,7,11,2]);[[6,0,40],[6,1,41],[6,3,43],[6,5,45],[6,8,48],[6,12,52],[5,3,48],[4,10,60],[2,1,60],[1,8,72]].forEach(([s,f,m])=>eq(`弦${s}品${f}`,M.Fretboard.position(M.TUNINGS.standard.midi,s,f).midi,m));return {passed:16-failures.length,failed:failures.length,failures}}};
  function init(){fillSelects();applyValues(defaults);bind();setTheme(localStorage.getItem('gat-theme')||'dark');generate();document.body.dataset.coreTests=JSON.stringify(window.GAT_TESTS.run());}
  window.addEventListener('DOMContentLoaded',init);
})();
