(function () {
  'use strict';
  const T=window.MelodyTheory, A=window.MelodyAudio, S=window.MelodyStore;
  let active=null;

  function now(){return performance.now()}
  function selectedValues(root,selector){return Array.from(root.querySelectorAll(selector+':checked')).map(x=>x.value)}
  function statsMini(){const s=S.data.stats, acc=s.total?Math.round(s.correct/s.total*100):0, avg=s.total?Math.round(s.totalMs/s.total/100)/10:0;return `<div class="divider"></div><div class="session-mini"><div><b>${s.total}</b><span>累计题目</span></div><div><b>${acc}%</b><span>正确率</span></div><div><b>${avg}s</b><span>平均反应</span></div></div>`}
  function playOrb(root,play){const b=root.querySelector('.play-orb');if(!b)return; b.classList.add('playing');Promise.resolve(play()).finally(()=>b.classList.remove('playing'))}
  function feedback(root,good,title,text){const el=root.querySelector('.feedback');el.className='feedback '+(good?'good':'bad');el.innerHTML=`<strong>${title}</strong>${text||''}`}
  function emit(result){S.record(result);if(window.MelodyApp&&window.MelodyApp.onTrainingResult)window.MelodyApp.onTrainingResult(result)}
  function checks(items,name,selected){return items.map(x=>`<label class="check-chip"><input type="checkbox" name="${name}" value="${x.id||x}" ${selected.includes(x.id||x)?'checked':''}><span>${x.id||x}</span></label>`).join('')}
  function trainerHead(eyebrow,title,desc){return `<div class="page-head"><div><div class="eyebrow">${eyebrow}</div><h1>${title}</h1><p>${desc}</p></div><div class="date-line">空格键播放 · 数字键可作答</div></div>`}
  function shell(stage,controls){return `<div class="trainer-layout"><section class="card stage">${stage}</section><aside class="card control-panel">${controls}</aside></div>`}
  function bindSpace(root,fn){const h=e=>{if(e.code==='Space'&&!/INPUT|TEXTAREA|SELECT/.test(e.target.tagName)){e.preventDefault();fn()}};document.addEventListener('keydown',h);return()=>document.removeEventListener('keydown',h)}

  function mountSingle(root){
    let state={mode:(S.data.custom.singleMode||'sing'),range:'basic',delay:0,q:null,plays:0,start:0,answered:false};
    root.innerHTML=trainerHead('MODULE A · ONE NOTE','把一个音，真正留在脑中','先听准、记住、唱回，再把它映射到级数和指板。音名识别只作为自由工具。')+`<div id="singleBody"></div>`;
    const body=root.querySelector('#singleBody');
    const render=()=>{
      const modeNames={sing:'单音模唱',memory:'音高记忆',match:'音高匹配',name:'音名识别',fret:'吉他定位'};
      let answer='';
      if(state.mode==='match')answer=`<div class="choices"><button class="choice" data-answer="same">相同</button><button class="choice" data-answer="different">不同</button></div>`;
      if(state.mode==='name')answer=`<div class="choices">${T.NOTE_NAMES.map(n=>`<button class="choice" data-answer="${n}">${n}</button>`).join('')}</div>`;
      if(state.mode==='sing'||state.mode==='memory')answer=`<div class="choices self-check" hidden><button class="choice" data-answer="yes">我唱准了</button><button class="choice" data-answer="no">还不稳定</button></div>`;
      if(state.mode==='fret')answer=fretboardHTML();
      body.innerHTML=shell(`<div class="stage-kicker">${modeNames[state.mode]} · 第 ${S.data.abilities[state.mode==='fret'?'fretMap':state.mode==='memory'?'pitchMemory':'singleSing'].attempts+1} 题</div><h2>${state.mode==='sing'?'听完后，用声音把它找回来':state.mode==='memory'?'让音高在脑中停留':state.mode==='match'?'第二个音，相同吗？':state.mode==='name'?'这个音叫什么？':'把听到的音落到指板'}</h2><div class="stage-note">${state.mode==='memory'&&state.delay?`播放后等待 ${state.delay} 秒再唱`:state.mode==='fret'?'点击任意一个同音名位置':'先不要急着猜，听完整个声音'}</div><button class="play-orb" aria-label="播放题目"></button><div class="answer-zone">${answer}<div class="feedback">点击播放，开始这一题</div></div><div class="trainer-actions"><button class="btn btn-ghost replay">↻ 再听一次</button>${state.mode==='sing'||state.mode==='memory'?'<button class="btn btn-primary reveal">播放原音并比较</button>':''}<button class="btn next">下一题 →</button></div>`, `<h3>单音训练设置</h3><div class="field"><span class="field-label">训练方式</span><div class="segmented" style="--cols:2">${Object.entries(modeNames).map(([k,v])=>`<button data-mode="${k}" class="${state.mode===k?'active':''}">${v}</button>`).join('')}</div></div><div class="field"><label>音域</label><select class="select" id="singleRange"><option value="basic" ${state.range==='basic'?'selected':''}>初级 · C4—C5</option><option value="wide">进阶 · C3—C5</option><option value="full">高级 · C2—C6</option></select></div>${state.mode==='memory'?`<div class="field"><label>保持时间</label><select class="select" id="singleDelay">${[0,2,4,6].map(n=>`<option value="${n}" ${state.delay===n?'selected':''}>${n?n+' 秒':'马上唱'}</option>`).join('')}</select></div>`:''}<div class="privacy-note">浏览器不会录音或判断你的嗓音。模唱题采用诚实自评：比较原音后记录感受。</div>${statsMini()}`);
      bind(); newQuestion();
    };
    const noteRange=()=>state.range==='basic'?[60,72]:state.range==='wide'?[48,72]:[36,84];
    const newQuestion=()=>{const [lo,hi]=noteRange(),midi=T.randomInt(lo,hi);state.q={midi,second:midi};if(state.mode==='match'){const same=Math.random()<.5,delta=T.pick([-5,-4,-3,-2,-1,1,2,3,4,5]);state.q.same=same;state.q.second=same?midi:T.clamp(midi+delta,lo,hi)}state.plays=0;state.start=0;state.answered=false;const fb=body.querySelector('.feedback');if(fb){fb.className='feedback';fb.textContent='点击播放，开始这一题'}body.querySelectorAll('.choice').forEach(x=>x.classList.remove('correct','wrong'));};
    const play=()=>{state.plays++;if(!state.start)state.start=now();if(state.mode==='match')return A.playSequence([state.q.midi,state.q.second],{noteDuration:.72,gap:.55});return A.playNote(state.q.midi,.9)};
    const answer=(value,button)=>{if(state.answered||!state.start)return;let correct=false,ability='singleSing';if(state.mode==='match'){correct=(value==='same')===state.q.same;ability='pitchMemory'}else if(state.mode==='name'){correct=value.replace('b','#')===T.pcName(state.q.midi%12).replace('b','#')||value===T.pcName(state.q.midi%12);ability='singleSing'}else{correct=value==='yes';ability=state.mode==='memory'?'pitchMemory':'singleSing'}state.answered=true;button&&button.classList.add(correct?'correct':'wrong');feedback(body,correct,correct?'很好，声音留住了':'先别追求速度',`答案：${T.noteName(state.q.midi,true)}`);emit({ability,correct,ms:now()-state.start,plays:state.plays,detail:state.mode})};
    const bind=()=>{
      body.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>{state.mode=b.dataset.mode;S.set('custom.singleMode',state.mode);render()});
      body.querySelector('#singleRange').onchange=e=>{state.range=e.target.value;newQuestion()}; const d=body.querySelector('#singleDelay');if(d)d.onchange=e=>state.delay=Number(e.target.value);
      body.querySelector('.play-orb').onclick=()=>playOrb(body,play);body.querySelector('.replay').onclick=()=>playOrb(body,play);body.querySelector('.next').onclick=()=>{newQuestion()};
      const reveal=body.querySelector('.reveal');if(reveal)reveal.onclick=()=>{A.playNote(state.q.midi,.95);const sc=body.querySelector('.self-check');sc.hidden=false};
      body.querySelectorAll('[data-answer]').forEach(b=>b.onclick=()=>answer(b.dataset.answer,b));
      body.querySelectorAll('.fret-cell button').forEach(b=>b.onclick=()=>{if(state.answered||!state.start)return;const midi=T.guitarNote(Number(b.dataset.string),Number(b.dataset.fret)),correct=midi%12===state.q.midi%12;state.answered=true;b.classList.add(correct?'correct':'selected');feedback(body,correct,correct?'找到了！':'位置还差一点',`目标是 ${T.noteName(state.q.midi,false)}，绿色位置都是同音名。`);if(!correct)T.guitarPositions(state.q.midi,12).forEach(p=>{const x=body.querySelector(`[data-string="${p.string}"][data-fret="${p.fret}"]`);if(x)x.classList.add('correct')});emit({ability:'fretMap',correct,ms:now()-state.start,plays:state.plays,detail:'fret'})});
    };
    render(); active={cleanup:bindSpace(root,()=>playOrb(body,play))};
  }

  function fretboardHTML(){return `<div class="fret-wrap"><div class="fretboard">${T.STRINGS.map((open,s)=>Array.from({length:13},(_,f)=>`<div class="fret-cell"><button data-string="${s}" data-fret="${f}" ${f===0?'class="string-name"':''}>${T.noteName(open+f,false)}</button></div>`).join('')).join('')}</div></div>`}

  function mountInterval(root){
    let state={mode:'identify',direction:'up',form:'melodic',selected:['m2','M2','m3','M3'],q:null,plays:0,start:0,answered:false};
    root.innerHTML=trainerHead('MODULE B · RELATION','听见两个音之间的距离','音程不是终点，它帮你听清旋律每一步走了多远。')+`<div id="intervalBody"></div>`;const body=root.querySelector('#intervalBody');
    const render=()=>{body.innerHTML=shell(`<div class="stage-kicker">${state.mode==='sing'?'音程构唱':'混合辨认'} · ${state.direction==='up'?'上行':state.direction==='down'?'下行':'和声'}</div><h2>${state.mode==='sing'?'听根音，唱出目标音程':'这两个音相隔多远？'}</h2><div class="stage-note">${state.mode==='sing'?'目标将在播放后显示':'先感受距离，再选择名称'}</div><button class="play-orb" aria-label="播放音程"></button><div class="answer-zone">${state.mode==='identify'?`<div class="choices">${state.selected.map(id=>`<button class="choice" data-answer="${id}">${id}</button>`).join('')}</div>`:`<div class="feedback sing-prompt">播放根音后显示构唱任务</div><div class="choices self-check" hidden><button class="choice" data-answer="yes">唱准了</button><button class="choice" data-answer="no">还没唱稳</button></div>`}<div class="feedback">点击播放，开始这一题</div></div><div class="trainer-actions"><button class="btn btn-ghost replay">↻ 再听一次</button>${state.mode==='sing'?'<button class="btn btn-primary compare">播放答案</button>':''}<button class="btn next">下一题 →</button></div>`, `<h3>音程训练设置</h3><div class="field"><span class="field-label">训练方式</span><div class="segmented"><button data-mode="identify" class="${state.mode==='identify'?'active':''}">听辨</button><button data-mode="sing" class="${state.mode==='sing'?'active':''}">构唱</button></div></div><div class="field"><span class="field-label">播放方式</span><div class="segmented" style="--cols:3"><button data-dir="up" class="${state.direction==='up'?'active':''}">上行</button><button data-dir="down" class="${state.direction==='down'?'active':''}">下行</button><button data-dir="harmonic" class="${state.direction==='harmonic'?'active':''}">和声</button></div></div><div class="field"><span class="field-label">选择音程</span><div class="check-grid">${checks(T.INTERVALS,'interval',state.selected)}</div><div class="preset-row" style="margin-top:8px"><button class="preset" data-preset="small">小跨度</button><button class="preset" data-preset="medium">中跨度</button><button class="preset" data-preset="large">大跨度</button><button class="preset" data-preset="all">全选</button></div></div>${statsMini()}`);bind();newQuestion()};
    const newQuestion=()=>{if(!state.selected.length)state.selected=['M2'];const id=T.pick(state.selected),interval=T.intervalById(id),rootMidi=T.randomInt(50,67);state.q={id,interval,root:rootMidi};state.plays=0;state.start=0;state.answered=false;body.querySelectorAll('.choice').forEach(x=>x.classList.remove('correct','wrong'));const fb=body.querySelectorAll('.feedback');fb.forEach(x=>{x.className='feedback';x.textContent=state.mode==='sing'?'播放根音，准备构唱':'点击播放，开始这一题'})};
    const play=()=>{state.plays++;if(!state.start)state.start=now();if(state.mode==='sing'){const p=body.querySelector('.sing-prompt');if(p)p.innerHTML=`<strong>唱：${state.direction==='down'?'下方':'上方'} ${state.q.id}</strong>从 ${T.noteName(state.q.root,true)} 出发`;return A.playNote(state.q.root,.85)}return A.playInterval(state.q.root,state.q.interval.semitones,state.direction==='down'?'down':'up',state.direction==='harmonic'?'harmonic':'melodic')};
    const answer=(v,b)=>{if(state.answered||!state.start)return;const correct=state.mode==='sing'?v==='yes':v===state.q.id;state.answered=true;b.classList.add(correct?'correct':'wrong');feedback(body,correct,correct?'距离听清了':'再把两个音在脑中靠近一点',`${state.q.id} · ${state.q.interval.name} · ${state.q.interval.semitones} 个半音`);emit({ability:state.mode==='sing'?'intervalSing':'intervalHear',correct,ms:now()-state.start,plays:state.plays,detail:state.q.id})};
    const bind=()=>{body.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>{state.mode=b.dataset.mode;render()});body.querySelectorAll('[data-dir]').forEach(b=>b.onclick=()=>{state.direction=b.dataset.dir;render()});body.querySelectorAll('input[name=interval]').forEach(c=>c.onchange=()=>{state.selected=selectedValues(body,'input[name=interval]');render()});body.querySelectorAll('[data-preset]').forEach(b=>b.onclick=()=>{const m={small:['m2','M2','m3','M3'],medium:['P4','TT','P5'],large:['m6','M6','m7','M7','P8'],all:T.INTERVALS.map(x=>x.id)};state.selected=m[b.dataset.preset];render()});body.querySelector('.play-orb').onclick=()=>playOrb(body,play);body.querySelector('.replay').onclick=()=>playOrb(body,play);body.querySelector('.next').onclick=newQuestion;const compare=body.querySelector('.compare');if(compare)compare.onclick=()=>{const target=state.direction==='down'?state.q.root-state.q.interval.semitones:state.q.root+state.q.interval.semitones;A.playSequence([state.q.root,target],{noteDuration:.7,gap:.25});body.querySelector('.self-check').hidden=false};body.querySelectorAll('[data-answer]').forEach(b=>b.onclick=()=>answer(b.dataset.answer,b))};
    render();active={cleanup:bindSpace(root,()=>playOrb(body,play))};
  }

  function mountDegree(root){
    let state={mode:(window.MelodyApp&&window.MelodyApp.getGuidedMode&&window.MelodyApp.getGuidedMode()==='degreeSing')?'sing':'hear',key:'C',keys:['C','G','F'],selected:[1,2,3,5],q:null,plays:0,start:0,answered:false};
    root.innerHTML=trainerHead('MODULE C · FUNCTION','听见一个音在调里的身份','音名会变，但“家”的感觉不变。先建立调中心，再听级数。')+`<div id="degreeBody"></div>`;const body=root.querySelector('#degreeBody');
    const render=()=>{body.innerHTML=shell(`<div class="stage-kicker">${state.key} MAJOR · ${state.mode==='hear'?'听 → 级数':'级数 → 唱'}</div><h2>${state.mode==='hear'?'这个音，是几级？':'看到级数，直接唱出它'}</h2><div class="stage-note">先用「建立调中心」找到家的感觉</div><button class="play-orb" aria-label="播放目标音"></button><div class="answer-zone">${state.mode==='hear'?`<div class="choices">${state.selected.map(d=>`<button class="choice" data-answer="${d}">${d}</button>`).join('')}</div>`:`<div class="feedback degree-prompt">点击播放主音后显示目标级数</div><div class="choices self-check" hidden><button class="choice" data-answer="yes">唱准了</button><button class="choice" data-answer="no">还要找音阶</button></div>`}<div class="feedback">先建立调中心，再开始答题</div></div><div class="trainer-actions"><button class="btn establish">♬ 建立调中心</button><button class="btn btn-ghost replay">↻ 再听</button>${state.mode==='sing'?'<button class="btn btn-primary compare">播放答案</button>':''}<button class="btn next">下一题 →</button></div>`, `<h3>级数训练设置</h3><div class="field"><span class="field-label">训练方向</span><div class="segmented"><button data-mode="hear" class="${state.mode==='hear'?'active':''}">听 → 级数</button><button data-mode="sing" class="${state.mode==='sing'?'active':''}">级数 → 唱</button></div></div><div class="field"><label>当前调</label><select class="select key-select">${T.KEYS.map(k=>`<option ${k===state.key?'selected':''}>${k}</option>`).join('')}</select><div class="preset-row" style="margin-top:7px"><button class="preset random-key">在 C / G / F 中随机</button></div></div><div class="field"><span class="field-label">可用级数</span><div class="check-grid">${checks([1,2,3,4,5,6,7].map(id=>({id})),'degree',state.selected)}</div></div>${statsMini()}`);bind();newQuestion()};
    const newQuestion=()=>{if(!state.selected.length)state.selected=[1];const degree=T.pick(state.selected),rootMidi=T.keyRootMidi(state.key,60);state.q={degree,root:rootMidi,midi:T.degreeMidi(rootMidi,degree)};state.start=0;state.plays=0;state.answered=false;body.querySelectorAll('.choice').forEach(x=>x.classList.remove('correct','wrong'));const f=body.querySelectorAll('.feedback');f.forEach(x=>{x.className='feedback';x.textContent=state.mode==='sing'?'先听主音，准备构唱':'先建立调中心，再开始答题'})};
    const play=()=>{state.plays++;if(!state.start)state.start=now();if(state.mode==='sing'){body.querySelector('.degree-prompt').innerHTML=`<strong>唱：${state.q.degree}</strong>不要先顺着音阶数过去`;return A.playNote(state.q.root,.9)}return A.playNote(state.q.midi,.9)};
    const answer=(v,b)=>{if(state.answered||!state.start)return;const correct=state.mode==='sing'?v==='yes':Number(v)===state.q.degree;state.answered=true;b.classList.add(correct?'correct':'wrong');feedback(body,correct,correct?'听见了它在“家”里的位置':'回到主音，再感受一次',`${state.key} 大调的 ${state.q.degree} 级是 ${T.noteName(state.q.midi,false)}`);emit({ability:state.mode==='sing'?'degreeSing':'degreeHear',correct,ms:now()-state.start,plays:state.plays,detail:state.key+' '+state.q.degree})};
    const bind=()=>{body.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>{state.mode=b.dataset.mode;render()});body.querySelector('.key-select').onchange=e=>{state.key=e.target.value;render()};body.querySelector('.random-key').onclick=()=>{state.key=T.pick(state.keys);render()};body.querySelectorAll('input[name=degree]').forEach(c=>c.onchange=()=>{state.selected=selectedValues(body,'input[name=degree]').map(Number);render()});body.querySelector('.establish').onclick=()=>playOrb(body,()=>A.playCadence(state.key));body.querySelector('.play-orb').onclick=()=>playOrb(body,play);body.querySelector('.replay').onclick=()=>playOrb(body,play);body.querySelector('.next').onclick=newQuestion;const compare=body.querySelector('.compare');if(compare)compare.onclick=()=>{A.playSequence([state.q.root,state.q.midi],{noteDuration:.75,gap:.3});body.querySelector('.self-check').hidden=false};body.querySelectorAll('[data-answer]').forEach(b=>b.onclick=()=>answer(b.dataset.answer,b))};
    render();active={cleanup:bindSpace(root,()=>playOrb(body,play))};
  }

  function mountMelody(root){
    let state={mode:'write',difficulty:1,key:'C',length:3,degrees:[1,2,3,5],maxLeap:4,custom:false,delay:0,maxPlays:3,input:'degree',q:null,plays:0,start:0,answered:false,entered:[]};
    root.innerHTML=trainerHead('MODULE D · PHRASE','把几个音，听成一个旋律单位','这里是训练核心：轮廓、模唱、级数听写和短期旋律记忆在这里汇合。')+`<div id="melodyBody"></div>`;const body=root.querySelector('#melodyBody');
    let render=()=>{let input='';if(state.mode==='contour')input=`<div class="sequence-input">${['↑','→','↓'].map(x=>`<button class="sequence-token" data-token="${x}">${x}</button>`).join('')}</div>`;else if(state.mode==='sing')input=`<div class="choices self-check"><button class="choice" data-self="yes">完整唱回来了</button><button class="choice" data-self="no">中间有断点</button></div>`;else if(state.input==='degree')input=`<div class="sequence-input">${[1,2,3,4,5,6,7].map(x=>`<button class="sequence-token" data-token="${x}">${x}</button>`).join('')}</div>`;else if(state.input==='piano')input=keyboardHTML();else input=fretboardHTML();
      body.innerHTML=shell(`<div class="stage-kicker">DIFFICULTY ${state.difficulty}${state.custom?' · 自定义':''} · ${state.key} MAJOR · ${state.length} 音</div><h2>${state.mode==='contour'?'只听旋律的方向':state.mode==='sing'?'听完，完整唱回来':'听写这句短旋律'}</h2><div class="stage-note">${state.delay?`播放后保持 ${state.delay} 秒，回答区才会开放`:`最多播放 ${state.maxPlays===0?'不限':state.maxPlays} 次`}</div><button class="play-orb" aria-label="播放短旋律"></button><div class="answer-zone"><div class="sequence-preview"></div><div class="input-area">${input}</div><div class="feedback">先完整听一遍，不要边播边猜</div></div><div class="trainer-actions"><button class="btn btn-ghost clear">清空</button>${state.mode!=='sing'?'<button class="btn btn-primary submit">提交答案</button>':''}<button class="btn next">下一题 →</button></div>`, `<h3>短旋律设置</h3><div class="field"><span class="field-label">训练方式</span><div class="segmented" style="--cols:3"><button data-mode="write" class="${state.mode==='write'?'active':''}">级数听写</button><button data-mode="contour" class="${state.mode==='contour'?'active':''}">轮廓</button><button data-mode="sing" class="${state.mode==='sing'?'active':''}">模唱</button></div></div><div class="field"><label>难度 · <b>${state.difficulty}</b></label><input class="range difficulty" type="range" min="1" max="5" value="${state.difficulty}"><div class="range-row"><span>3音 / 1·2·3·5</span><span>完整1—7</span></div></div><div class="field"><label>音数</label><select class="select length">${[3,4,5,6,8].map(n=>`<option value="${n}" ${n===state.length?'selected':''}>${n} 个音</option>`).join('')}</select></div><div class="field"><label>记忆延迟</label><select class="select delay">${[0,2,4,6].map(n=>`<option value="${n}" ${n===state.delay?'selected':''}>${n?n+' 秒':'无延迟'}</option>`).join('')}</select></div><div class="field"><label>最多播放</label><select class="select maxplays">${[['0','不限'],['5','5 次'],['3','3 次'],['2','2 次'],['1','只听 1 次']].map(([v,n])=>`<option value="${v}" ${Number(v)===state.maxPlays?'selected':''}>${n}</option>`).join('')}</select></div>${state.mode==='write'?`<div class="field"><span class="field-label">输入方式</span><div class="segmented" style="--cols:3"><button data-input="degree" class="${state.input==='degree'?'active':''}">数字级数</button><button data-input="piano" class="${state.input==='piano'?'active':''}">虚拟钢琴</button><button data-input="fret" class="${state.input==='fret'?'active':''}">吉他指板</button></div></div>`:''}${statsMini()}`);bind();newQuestion()};
    const baseRender=render;
    render=()=>{baseRender();const divider=body.querySelector('.control-panel .divider');if(!divider)return;divider.insertAdjacentHTML('beforebegin',`<div class="field"><label>当前调</label><select class="select melody-key">${T.KEYS.map(k=>`<option ${k===state.key?'selected':''}>${k}</option>`).join('')}</select></div><div class="field"><span class="field-label">自定义可用级数</span><div class="check-grid">${checks([1,2,3,4,5,6,7].map(id=>({id})),'melodyDegree',state.degrees)}</div></div><div class="field"><label>最大跳进</label><select class="select max-leap">${[['2','M2'],['4','M3'],['5','P4'],['7','P5'],['12','P8']].map(([v,n])=>`<option value="${v}" ${Number(v)===state.maxLeap?'selected':''}>${n}</option>`).join('')}</select></div>`);body.querySelector('.melody-key').onchange=e=>{state.key=e.target.value;render()};body.querySelectorAll('input[name=melodyDegree]').forEach(c=>c.onchange=()=>{state.degrees=selectedValues(body,'input[name=melodyDegree]').map(Number);state.custom=true;render()});body.querySelector('.max-leap').onchange=e=>{state.maxLeap=Number(e.target.value);state.custom=true;render()}};
    const difficultyConfig=()=>{const cfg={1:{degrees:[1,2,3,5],maxLeap:4},2:{degrees:[1,2,3,5,6],maxLeap:4},3:{degrees:[1,2,3,4,5,6],maxLeap:5},4:{degrees:[1,2,3,4,5,6,7],maxLeap:7},5:{degrees:[1,2,3,4,5,6,7],maxLeap:12}};return cfg[state.difficulty]};
    const newQuestion=()=>{if(!state.custom){const cfg=difficultyConfig();state.degrees=cfg.degrees;state.maxLeap=cfg.maxLeap}if(!state.degrees.length)state.degrees=[1];state.q=T.generateMelody({difficulty:state.difficulty,length:state.length,degrees:state.degrees,maxLeap:state.maxLeap,key:state.key,stepProbability:state.difficulty<3?.8:.62});state.entered=[];state.plays=0;state.start=0;state.answered=false;updatePreview();const fb=body.querySelector('.feedback');fb.className='feedback';fb.textContent='先完整听一遍，不要边播边猜'};
    const updatePreview=()=>{const p=body.querySelector('.sequence-preview');if(p)p.innerHTML=state.entered.map(x=>`<span>${x}</span>`).join('')};
    const play=()=>{if(state.maxPlays&&state.plays>=state.maxPlays){feedback(body,false,'已经达到播放上限','试着用脑中留下的声音作答。');return Promise.resolve()}state.plays++;if(!state.start)state.start=now();return A.playSequence(state.q.midi,{noteDuration:.46,gap:.11})};
    const token=v=>{if(state.answered||!state.start)return;if(state.mode==='contour'&&state.entered.length>=state.q.degrees.length-1)return;if(state.mode!=='contour'&&state.entered.length>=state.q.degrees.length)return;state.entered.push(isNaN(Number(v))?v:Number(v));updatePreview()};
    const submit=()=>{if(state.answered||!state.start)return;const target=state.mode==='contour'?T.contour(state.q.midi):state.q.degrees,correct=target.length===state.entered.length&&target.every((x,i)=>String(x)===String(state.entered[i]));state.answered=true;feedback(body,correct,correct?'你听见的是一个整体':'保留轮廓，再补每个音的位置',`答案：${target.join(' · ')}　平均播放 ${state.plays} 次`);emit({ability:state.mode==='contour'?'melodyMemory':'melodyWrite',correct,ms:now()-state.start,plays:state.plays,detail:state.q.degrees.join(' ')})};
    const self=v=>{if(state.answered||!state.start)return;state.answered=true;const correct=v==='yes';feedback(body,correct,correct?'旋律留在脑中了':'把旋律分成更小的动机再唱',`级数答案：${state.q.degrees.join(' · ')}`);emit({ability:'melodyMemory',correct,ms:now()-state.start,plays:state.plays,detail:'sing '+state.q.degrees.join(' ')})};
    const bind=()=>{body.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>{state.mode=b.dataset.mode;render()});body.querySelectorAll('[data-input]').forEach(b=>b.onclick=()=>{state.input=b.dataset.input;render()});body.querySelector('.difficulty').oninput=e=>{state.difficulty=Number(e.target.value);state.custom=false;const cfg=difficultyConfig();state.degrees=cfg.degrees;state.maxLeap=cfg.maxLeap;render()};const keySelect=body.querySelector('.melody-key');if(keySelect)keySelect.onchange=e=>{state.key=e.target.value;render()};body.querySelector('.length').onchange=e=>{state.length=Number(e.target.value);render()};body.querySelectorAll('input[name=melodyDegree]').forEach(c=>c.onchange=()=>{state.degrees=selectedValues(body,'input[name=melodyDegree]').map(Number);state.custom=true;render()});const leap=body.querySelector('.max-leap');if(leap)leap.onchange=e=>{state.maxLeap=Number(e.target.value);state.custom=true;render()};body.querySelector('.delay').onchange=e=>{state.delay=Number(e.target.value);render()};body.querySelector('.maxplays').onchange=e=>{state.maxPlays=Number(e.target.value);render()};body.querySelector('.play-orb').onclick=()=>playOrb(body,play);body.querySelector('.clear').onclick=()=>{state.entered.pop();updatePreview()};body.querySelector('.next').onclick=newQuestion;const submitBtn=body.querySelector('.submit');if(submitBtn)submitBtn.onclick=submit;body.querySelectorAll('[data-token]').forEach(b=>b.onclick=()=>token(b.dataset.token));body.querySelectorAll('[data-self]').forEach(b=>b.onclick=()=>self(b.dataset.self));body.querySelectorAll('.key[data-degree]').forEach(b=>b.onclick=()=>token(b.dataset.degree));body.querySelectorAll('.fret-cell button').forEach(b=>b.onclick=()=>{const midi=T.guitarNote(Number(b.dataset.string),Number(b.dataset.fret)),pc=(midi-state.q.root+120)%12,degree=T.MAJOR_STEPS.indexOf(pc)+1;if(degree>0)token(degree);else feedback(body,false,'这是调外音','当前版本默认训练自然大调 1—7。')})};
    render();active={cleanup:bindSpace(root,()=>playOrb(body,play))};
  }
  function keyboardHTML(){return `<div class="keyboard">${[1,2,3,4,5,6,7,1].map((d,i)=>`<button class="key" data-degree="${d}">${d}</button>${[1,2,4,5,6].includes(d)&&i<7?'<button class="key black" tabindex="-1" disabled aria-hidden="true">·</button>':''}`).join('')}</div>`}

  function cleanup(){if(active&&active.cleanup)active.cleanup();active=null;A.stopAll()}
  window.MelodyTrainers={mountSingle,mountInterval,mountDegree,mountMelody,cleanup,fretboardHTML};
})();
